// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDZaA_JKW6LVcLZsT87Kd2wXEVpsUBdhI',
    appId: '1:1044488601481:web:c2d8af96cb51f3375d6b58',
    messagingSenderId: '1044488601481',
    projectId: 'store-app-1feb7',
    authDomain: 'store-app-1feb7.firebaseapp.com',
    storageBucket: 'store-app-1feb7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAECi-jiPHhQv53cWm_KR691QN2mI1fpOI',
    appId: '1:1044488601481:android:a5eff0c0dcb00b735d6b58',
    messagingSenderId: '1044488601481',
    projectId: 'store-app-1feb7',
    storageBucket: 'store-app-1feb7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvhkkVkWPcSB7-ZYRXB9bWHwsejSLJRU4',
    appId: '1:1044488601481:ios:16a5dbed4bba459e5d6b58',
    messagingSenderId: '1044488601481',
    projectId: 'store-app-1feb7',
    storageBucket: 'store-app-1feb7.appspot.com',
    iosClientId: '1044488601481-4rs9otvg4jjvus61nc97f6n04ob730cu.apps.googleusercontent.com',
    iosBundleId: 'com.example.storeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvhkkVkWPcSB7-ZYRXB9bWHwsejSLJRU4',
    appId: '1:1044488601481:ios:16a5dbed4bba459e5d6b58',
    messagingSenderId: '1044488601481',
    projectId: 'store-app-1feb7',
    storageBucket: 'store-app-1feb7.appspot.com',
    iosClientId: '1044488601481-4rs9otvg4jjvus61nc97f6n04ob730cu.apps.googleusercontent.com',
    iosBundleId: 'com.example.storeApp',
  );
}
